# Navigation Links

[[main]]
  name = "Home"
  url = "#about"
  weight = 1

[[main]]
  name = "Publications"
  url = "#featured"
  weight = 2

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 3

[[main]]
  name = "Teaching"
  url = "#teaching"
  weight = 4

[[main]]
  name = "Experience"
  url = "experience/"
  weight = 5


[[main]]
  name = "Medium"
  url = "medium/"
  weight = 6


[[main]]
  name = "Contact"
  url = "#contact"
  weight = 7
