# SITE SETUP

# Color theme.
#   Choose from `default`, `ocean`, `forest`, `dark`, `apogee`, `1950s`, `coffee`, `cupcake`, `strawberry`.
color_theme = "default"
day_night = false

# Font style.
#   Choose from `default`, `classic`, or `playfair`.
font = "default"

# Description for social sharing and search engines. If undefined, superuser role is used in place.
description = ""

# Default image for social sharing and search engines. Place image in `static/img/` folder and specify image name here.
sharing_image = ""

# Twitter username (without @). Used when a vistor shares your site on Twitter.
twitter = "melvidoni"

# Diplay a logo in navigation bar rather than title (optional).
#   To enable, place an image in `static/img/` and reference its filename below. To disable, set the value to "".
logo = ""

# Enable global source code highlighting? true/false
  highlight = true
  highlight_languages = ["r", "yaml", "java", "css", "javascript"]
  highlight_style = "atelier-cave-light"
  highlight_version = "9.12.0"


# Enable global LaTeX math rendering?
#   If false, you can enable it locally on a per page basis.
math = false

# Privacy pack
#   Show a cookie consent message to visitors
#   Anonymize IP in Google Analytics (if enabled)
privacy_pack = false

# Date and time format
date_format = "Jan 2, 2006"
time_format = "3:04 PM"






############################
## Plugins                ##
############################

# Load CSS and JS plugins
#   E.g. To load `/assets/css/custom.css`, set `plugins_css = ["custom"]`.
#   E.g. To load `/assets/js/custom.js`, set `plugins_js = ["custom"]`.
plugins_css = ["custom"]
plugins_js  = ["script"]




############################
## Advanced options       ##
############################

# Get user avatars from Gravatar.com? (true/false)
gravatar = false

# Align the main menu to the right of the page? (true/false)
menu_align_right = true

# Show estimated reading time for posts? (true/false)
reading_time = false

# Display comment count (if commenting enabled in config.toml)? (true/false)
comment_count = false

# Display next/previous section pager? (true/false)
section_pager = false
docs_section_pager = false  # Display pager in Docs layout (e.g. tutorials)?

# Enable in-built social sharing buttons? (true/false)
sharing = true

# Configuration of publication pages.
[publications]
  date_format = "January 2006"
  citation_style = "apa"

# Configuration of project pages.
[projects]
  # Views for associated content.
  #   1: List
  #   2: Compact
  #   3: Card
  #   4: Citation (publications only)
  post_view = 2
  publication_view = 4
  talk_view = 2

# Search.
[search]
  # Search provider:
  #   0: No search engine
  #   1: Academic (built-in)
  #   2: Algolia (https://www.algolia.com)
  engine = 0
