---
title: 'MSR4P&S 2022 Workshop Summary'
authors: ["Melina Vidoni"]

abstract: "The 1st edition of the workshop on Mining Software Repositories for Privacy and Security (MSR4P&S 2022) was held virtually on November 18th, 2022, co-located with the 30th ACM Joint Meeting on European Software Engineering Conference and Symposium on the Foundations of Software Engineering (ESEC/FSE 2022), which took place in Singapore. MSR4P&S received a total of five submissions from diverse geographic locations, which were all included in the program after a rigorous peer-review process. The program also featured a keynote by M. Ali Babar on the quality of data mined for security research. This report summarises the event and insights stemming from the keynote and presentations in the workshop's two sessions."
  

date: "2023-01-14T00:00:00Z"
image_preview: ""
math: true
publication_types: ["3"]

publication: "In *ACM SIGSOFT Software Engineering Notes*, Vol 48(1)"
publication_short: "In *ACM SIGSOFT Software Engineering Notes*, Vol 48(1)"

featured: true

url_code: ""
url_dataset: ""
url_pdf: "publication/2023-msr4ps-sen.pdf"
url_project: ""
url_slides: ""
url_video: ""
doi: "10.1145/3573074.3573100"


# Projects (optional).
#projects:
#- 2020-rse

---

### Workshop Format

MSR4P&S received five submissions (two 8-page full papers and three 4-page short papers) from Canada, the United States, the UK, France, and Norway.  After a thorough peer-review process, all five papers were accepted and given an additional page to incorporate the changes suggested by the reviewers. At least three members of the Program Committee reviewed each submission. The  accepted  papers  cover  various  topics  and  are  divided  into two  main  sessions: _assessing privacy through mining software repositories_ and _using mining software repositories to detect or analyse vulnerabilities_.

The workshop proceedings are published by ACM as a co-located event of the 30th ACM Joint Meeting on European Software Engineering Conference and Symposium on the Foundations of Software Engineering (ESEC/FSE 2022) [See Proceedings](../2022-msr4ps/). The workshop was held on November 18th, 2022 and  had 45 participants. Due to the SARS-CoV-2 pandemic, the event took place virtually and was organised with this aspect in mind.  The program comprised the opening, one keynote, two presentation sessions, and theclosing. We planned two thematic sessions, "Assessing  Privacy" and "Vulnerabilities", based on the topics addressed by the accepted papers. Each talk of the thematic sessions had fifteen  minutes allocated for the presentation and five minutes for discussions.






### Citation

```
@article{MSR4PSsummary,
author = {Vidoni, Melina and D\'{\i}az Ferreyra, Nicol\'{a}s E. and Codabux, Zadia},
title = {MSR4P\&S 2022 Workshop Summary},
year = {2023},
issue_date = {January 2023},
publisher = {Association for Computing Machinery},
address = {New York, NY, USA},
volume = {48},
number = {1},
issn = {0163-5948},
doi = {10.1145/3573074.3573100},
journal = {SIGSOFT Softw. Eng. Notes},
month = {jan},
pages = {97–100},
numpages = {4}
}
```


